### ISSUE TITLE
$.now() is deprecated

### ISSUE THREAD

**Issue by danowar2k** [moodle-an-hochschulen/moodle-local_session_keepalive#6]
https://github.com/moodleuulm/moodle-local_session_keepalive/blob/4b5404bf8c460df5e416556913eb919d4b74639f/amd/src/keepalive.js#L36

Just a reminder to replace it with another call.

**Comment by abias** [comment]
This was solved now for the 4.0 release in 19d3f8437c187416f2ba19f072ee261a35a79581
